# Generated by Django 6.0.3 on 2026-03-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_system', '0002_alter_complaint_user_alter_group_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='calculated_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
